### ISSUE TITLE
[Bug]: enable_thinking=False doesn't work for Qwen/Qwen3-4B-MLX-4bit

### ISSUE THREAD

**Issue by Jessen-Li** [QwenLM/Qwen3#1625]
### Model Series

Qwen3

### What are the models used?

Qwen/Qwen3-4B-MLX-4bit

### What is the scenario where the problem happened?

just generate response

### Is this a known issue?

- [x] I have followed [the GitHub README](https://github.com/QwenLM/Qwen3).
- [x] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [x] I have checked the documentation of the related framework and cannot find useful information.
- [x] I have searched [the issues](https://github.com/QwenLM/Qwen3/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

Hardware: Apple M4 Pro,
OS: macOS Sequoia, version 15.5
tensorflow: 2.16.2
Python 3.10.16
PyTorch: 2.9.0.dev20250711

### Log output

```shell
<think>
Okay, the user wants me to introduce myself and explain what I can do. Let me start by recalling my name and role. I'm Qwen, a large-scale language model developed by Alibaba Cloud. I was trained on a vast amount of text data to understand and generate human-like text.

First, I should mention my main functions. I can answer questions, create content, and engage in conversations. But I need to be specific. For example, I can help with writing, translating, summarizing, and more. Also, I should highlight my ability to handle multiple tasks, like coding, creative writing, and problem-solving.

Wait, the user might be interested in how I work. I should explain that I use advanced algorithms and a massive dataset to generate responses. But I need to keep it simple and not too technical. Maybe mention that I can adapt to different tasks and maintain a conversational tone.

Also, I should include examples of what I can do. Like, writing an email, creating a story, or helping with a coding problem. But I should avoid being too verbose. The user might want a clear, concise overview.

I need to make sure the introduction is friendly and welcoming. Start with a greeting, then introduce my name and purpose. Then list the capabilities in a structured way. Maybe use bullet points or a numbered list for clarity. But since the user asked for a natural response, I should avoid markdown and keep it in plain text.

Also, check if there's anything I should not do. For example, I can't access real-time data or personal information. I should mention that I can't provide medical advice or legal opinions. But the user didn't ask about limitations, so maybe just focus on the positives.

Wait, the user might be looking for a more detailed breakdown. Let me structure it: start with a greeting, then my name and role, then list the main functions, and conclude with an invitation to ask questions. That should cover it.

I should also make sure the tone is helpful and approachable. Use phrases like "I'm here to help" or "I can assist with..." to encourage interaction. Avoid jargon and keep the language simple and conversational.
</think>
```

### Description

from mlx_lm import load, generate

def main():
  model,tokenizer = load("Qwen/Qwen3-4B-MLX-4bit")
  prompt = "Hello, please introduce yourself and tell me what you can do."

  if tokenizer.chat_template is not None:
     messages=[{"role":"user", "content":prompt}]
     prompt = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        enable_thinking=False
     )
     response = generate(
        model,
        tokenizer,
        prompt=prompt,
        verbose=False,
        max_tokens=1024
     )
     print(response)

**Comment by jklj077** [comment]
Thanks for bringing this issue to our attention. We have fixed the model files and please pull the latest version, in particular, the `tokenizer_config.json` file.

**Comment by siddhantoon** [comment]
@jklj077 This issue still exists. Here is the code I am running

```
tok = AutoTokenizer.from_pretrained("Qwen/Qwen3-4B-MLX-4bit")
x = [{'content': 'Recommend a movie to watch.\n', 'role': 'user'}, {'content': 'I would recommend the movie Shawshank',
   'role': 'assistant'}]
print(tok.apply_chat_template(x, enable_thinking=False, tokenize=False))
```
output
```
<|im_start|>user
Recommend a movie to watch.
<|im_end|>
<|im_start|>assistant
<think>

</think>

I would recommend the movie Shawshank<|im_end|>
```

Tried other tokenizers in Qwen-3 family all give same result. 

### So I checked the chat template - it seems to work fine so there is issue some other place.

```
from jinja2 import Template
import difflib

tmpl = """{%- if tools %}\n    {{- '<|im_start|>system\\n' }}\n    {%- if messages[0].role == 'system' %}\n        {{- messages[0].content + '\\n\\n' }}\n    {%- endif %}\n    {{- \"# Tools\\n\\nYou may call one or more functions to assist with the user query.\\n\\nYou are provided with function signatures within <tools></tools> XML tags:\\n<tools>\" }}\n    {%- for tool in tools %}\n        {{- \"\\n\" }}\n        {{- tool | tojson }}\n    {%- endfor %}\n    {{- \"\\n</tools>\\n\\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\\n<tool_call>\\n{\\\"name\\\": <function-name>, \\\"arguments\\\": <args-json-object>}\\n</tool_call><|im_end|>\\n\" }}\n{%- else %}\n    {%- if messages[0].role == 'system' %}\n        {{- '<|im_start|>system\\n' + messages[0].content + '<|im_end|>\\n' }}\n    {%- endif %}\n{%- endif %}\n{%- set ns = namespace(multi_step_tool=true, last_query_index=messages|length - 1) %}\n{%- for message in messages[::-1] %}\n    {%- set index = (messages|length - 1) - loop.index0 %}\n    {%- if ns.multi_step_tool and message.role == \"user\" and message.content is string and not(message.content.startswith('<tool_response>') and message.content.endswith('</tool_response>')) %}\n        {%- set ns.multi_step_tool = false %}\n        {%- set ns.last_query_index = index %}\n    {%- endif %}\n{%- endfor %}\n{%- for message in messages %}\n    {%- if message.content is string %}\n        {%- set content = message.content %}\n    {%- else %}\n        {%- set content = '' %}\n    {%- endif %}\n    {%- if (message.role == \"user\") or (message.role == \"system\" and not loop.first) %}\n        {{- '<|im_start|>' + message.role + '\\n' + content + '<|im_end|>' + '\\n' }}\n    {%- elif message.role == \"assistant\" %}\n        {%- set reasoning_content = '' %}\n        {%- if message.reasoning_content is string %}\n            {%- set reasoning_content = message.reasoning_content %}\n        {%- else %}\n            {%- if '</think>' in content %}\n                {%- set reasoning_content = content.split('</think>')[0].rstrip('\\n').split('<think>')[-1].lstrip('\\n') %}\n                {%- set content = content.split('</think>')[-1].lstrip('\\n') %}\n            {%- endif %}\n        {%- endif %}\n        {%- if loop.index0 > ns.last_query_index %}\n            {%- if loop.last or (not loop.last and reasoning_content) %}\n                {{- '<|im_start|>' + message.role + '\\n<think>\\n' + reasoning_content.strip('\\n') + '\\n</think>\\n\\n' + content.lstrip('\\n') }}\n            {%- else %}\n                {{- '<|im_start|>' + message.role + '\\n' + content }}\n            {%- endif %}\n        {%- else %}\n            {{- '<|im_start|>' + message.role + '\\n' + content }}\n        {%- endif %}\n        {%- if message.tool_calls %}\n            {%- for tool_call in message.tool_calls %}\n                {%- if (loop.first and content) or (not loop.first) %}\n                    {{- '\\n' }}\n                {%- endif %}\n                {%- if tool_call.function %}\n                    {%- set tool_call = tool_call.function %}\n                {%- endif %}\n                {{- '<tool_call>\\n{\"name\": \"' }}\n                {{- tool_call.name }}\n                {{- '\", \"arguments\": ' }}\n                {%- if tool_call.arguments is string %}\n                    {{- tool_call.arguments }}\n                {%- else %}\n                    {{- tool_call.arguments | tojson }}\n                {%- endif %}\n                {{- '}\\n</tool_call>' }}\n            {%- endfor %}\n        {%- endif %}\n        {{- '<|im_end|>\\n' }}\n    {%- elif message.role == \"tool\" %}\n        {%- if loop.first or (messages[loop.index0 - 1].role != \"tool\") %}\n            {{- '<|im_start|>user' }}\n        {%- endif %}\n        {{- '\\n<tool_response>\\n' }}\n        {{- content }}\n        {{- '\\n</tool_response>' }}\n        {%- if loop.last or (messages[loop.index0 + 1].role != \"tool\") %}\n            {{- '<|im_end|>\\n' }}\n        {%- endif %}\n    {%- endif %}\n{%- endfor %}\n{%- if add_generation_prompt %}\n    {{- '<|im_start|>assistant\\n' }}\n    {%- if enable_thinking is defined and enable_thinking is false %}\n        {{- '<think>\\n\\n</think>\\n\\n' }}\n    {%- endif %}\n{%- endif %}"""

base = {"tools": [], "messages": [{"role":"user","content":"Hello"}], "add_generation_prompt": True}

a = Template(tmpl).render(**{**base, "enable_thinking": False})
b = Template(tmpl).render(**{**base, "enable_thinking": True})
# print("\n".join(difflib.unified_diff(a.splitlines(), b.splitlines(), lineterm="")))
print(a)
print(b)
```

Output 
```
<|im_start|>user
Hello<|im_end|>
<|im_start|>assistant
<think>

</think>


<|im_start|>user
Hello<|im_end|>
<|im_start|>assistant
```

Here we pass `enable_thinking` flag & that works perfectly fine.

**Comment by jklj077** [comment]
All provided outputs in your comment are as expected. Open a new issue and describe what you expect. @siddhantoon

**Comment by siddhantoon** [comment]
@jklj077 
If I do enable_thinking=False the think tag block should not be present. But it is in the output. 
True false both ways the think tags are present in text.
How do I disable it. Like right now I'll need to do something manually like use regex to remove it.
